### ISSUE TITLE
Issues with gutters

### ISSUE THREAD

**Issue by Landish** [Coffeekraken/gridle#111]
Hi, 

I'm using the 2.0.46 version and I have the following code:

``` sass
// Setup Gridle.
@include gridle_setup(());

@include gridle_register_state(xs, (
        max-width : 750px,
        gutter-width: 20px,
        gutter-height: 20px
));

// some states here ... 

@include gridle_register_state(lg, (
        min-width : 1170px,
        gutter-width: 60px,
        gutter-height: 60px
));

// Generate all CSS classes.
@include gridle_generate_classes();

.container {
  max-width: $container-width;
  margin: 0 auto;
}
```

And in HTML:

``` html
<!--  some code-->
<div class="gr-4@sm">
  <!--  some codes-->
  <div class="row">
    <div class="gr-6@sm no-gutter@lg">
      <!--  some code-->
    </div>
    <div class="gr-6@sm no-gutter-top">
      <!--  some code-->
    </div>
  </div>
</div>
<!--  some code-->
```

It does not matter, I put the `.no-gutter` or `.no-gutter-top@xs` or other css class with any gutter direction and state prefix, It does not work, I mean it does not removes the gutters/paddings. Because the gutter removal classes and properties are overridden by this:

<img width="142" alt="screen shot 2016-05-24 at 1 13 54 pm" src="https://cloud.githubusercontent.com/assets/534610/15498622/6884ee78-21b1-11e6-9112-2b5e7c69f0f1.png">
<img width="80" alt="screen shot 2016-05-24 at 1 13 45 pm" src="https://cloud.githubusercontent.com/assets/534610/15498623/6885d2a2-21b1-11e6-90f2-c24166a92c2f.png">

You said here #100 that it was fixed, but I'm still not getting the results, I'm expected to see. I'm I doing something wrong here?

**Comment by dsteinel** [comment]
I am having exactly the same issue with version 2.0.47 and 2.0.48 also.
Is there any fix?

**Comment by bez4pieci** [comment]
The same issue still on v`2.0.48`

**Comment by GR3S** [comment]
Somebody found a workaround?

**Comment by vaidik** [comment]
+1. I am facing the same issue as well.

**Comment by olivierbossel** [comment]
Hi guys
First, thanks for your feedbacks. Appreciate that!
I will try to update the css generation order to make this work but it's quite complicated due to css selector weight concurrence.
You can test the 3.0.0-rc.2 as soon as it will be released (end of the week max) and give it a try.
Cheers!
