### ISSUE TITLE
gutter-top / gutter-bottom & gutter-height not working as expected.

### ISSUE THREAD

**Issue by sikeane** [Coffeekraken/gridle#114]
Trying to set 'gutter-top', 'gutter-bottom' or 'gutter-height' during default gridle_setup() is not working. e.g.

```
@include gridle_setup( (

    context: 12,
    gutter-width: 20px,
    gutter-top: 20px,
    gutter-bottom: 20px,

) );
```

The above correctly applies padding the width of the column but does not apply any padding top and bottom. Using only 'gutter-height' does the same.

However if you apply the settings when registering a state it works as expected e.g

```
@include gridle_register_state ( bp-s , (

    min-width: 600px,
    gutter-width: 20px,
    gutter-height: 20px


) );

```

The above applies padding to both the width and height of the column. This means columns inside of a state can have a gutter top and bottom.

**Comment by olivierbossel** [comment]
Hi,
Thanks for your feedback.
By default, the gutters that are applied on each grid items are only the side ones (left and right).
If you want to have the top and bottom gutter, you need to apply the "gutter" class on your grid item. This will apply all the 4 sides gutters.
The fact that all the gutters are applied on a state that has different gutters than the default ones is an issue and will be corrected in the next 3.0.0-rc.2 release that will be out soon.

The idea behind this behavior is that the major use cases, you will need gutters only left and right. The .gutter class will gives you the ability to set when you need the gutters to all sides.

In mixins use case, this will be done by doing something like so (3.0.0-rc.2)

```scss
.my-cool-grid-item {
   @include g-grid(6);
   @include g-gutter(all); // you can also pass : top right bottom left
}
```

Hope this make sense. If you have a better idea to handle that, let me know :)
Cheers!
