### ISSUE TITLE
Gridle.js events doesn't work when use mixins instead of classes

### ISSUE THREAD

**Issue by KhrystynaShekhovtsova** [Coffeekraken/gridle#115]
Hi there, I have an issue with Gridle.js and events. It just stopped working after changing classes to mixins :( 

Do you have any idea why could it happen?

Thanks in advance)

**Comment by olivierbossel** [comment]
Hi,
thanks for your feedback.
You will have to call the `g-generate-json-settings` (new name of the gridle_generate_json_settings mixin) in order to print out the json settings used by the gridle.js library inside your css file...
let me know!
Cheers
