### ISSUE TITLE
Clear Each classes don't cascade nicely

### ISSUE THREAD

**Issue by neonwired** [Coffeekraken/gridle#116]
For example : 

If we have two states and clear each setup as follows :

```
@include gridle_register_state (tablet, (  
    max-width : 768px  
));  
@include gridle_register_state (mobile, (  
    max-width : 414px  
));  
@include gridle_register_clear_each(2, both);  
@include gridle_register_clear_each(3, both);  
```

 if i have clear-each-3@tablet and clear-each-2@mobile on a row, below 414px width will be correctly  applying the clear-each-3 and clear-each-2 rules, however the final rule to be applied, clear-each-2, doesn't overrule the rules set by clear-each-3 and you end up with clearing on every 2nd and 3rd child breaking the layout.

One way workaround is to set a min-width on the tablet state e.g.

`@include gridle_register_state (tablet, (  
        min-width : 415px,  
        max-width : 768px  
));`

However, not only does this go against to principle of cascading, it also causes problems if, for example, the mobile state is added at a later date that the other states. It would mean that every single layout already using the grid would need altering to include the new 'mobile' state which is not very practical.

The best to solve this, in my opinion, is simply to have clear each reset the clears, so it's only clears the elements specified.

**Comment by olivierbossel** [comment]
Hi,
First, thanks for your feedback. Appreciate that!
I understand your issue and I come up to it quite often. I don't have had time to investigate until now.
I like your solution and I will apply it in the next 3.0.0-rc.2 release that will come out soon.
Really appreciate that someone come up with an issue and a solution. That's pretty rare these times :)
Have a nice day and check until the end of the week for the new release :)
Cheers!
