### ISSUE TITLE
Tips for better performance

### ISSUE THREAD

**Issue by klojniewski** [Coffeekraken/gridle#117]
Hello!
My team loves Gridle, but we have some performance issues (sass compilation time).
Do you have some best practises and list of things to avoid when using Gridle?

**Comment by olivierbossel** [comment]
Hi!
Thanks for your feedback!
My advices will be to avoid using the g-classes (new name for the gridle_generate_classes mixin) in your daily use scss file.
Make multiple files like so:

- _grid-settings.scss : setting up your grid with g-setup mixin, etc...
- _grid.scss : import the _grid-settings.scss file + generate the grid with g-classes mixin
- _style.scss : import the _grid-settings.scss file + your daily css stuffs

This is the g-classes mixin that take time to proceed cause it has to generate a lots of css. Simply avoif to run this every time you change your .scss files and you will be ok :)

Let me know!

Cheers!
