### ISSUE TITLE
Plugin error with gulp-sass 2.3.2

### ISSUE THREAD

**Issue by neonwired** [Coffeekraken/gridle#119]
When updating gulp-sass from 2.3.1 -> 2.3.2 gridle causes this error:

Error: Base-level rules cannot contain the parent-selector-referencing character '&'.

       Backtrace:
       	site/templates/assets/css/source/vendor/gridle/gridle/_mixins.scss:42, in mixin `-gridle-common-silent-class-name`
       	site/templates/assets/css/source/vendor/gridle/gridle/_mixins.scss:96, in mixin `-gridle-init-common-silent-classes`
       	site/templates/assets/css/source/vendor/gridle/gridle/_mixins.scss:25, in mixin `gridle-init`
       	site/templates/assets/css/source/vendor/gridle/gridle/_generate-mixins.scss:438, in mixin `gridle-generate-classes`
       	site/templates/assets/css/source/base/_gridle.scss:2
        on line 42 of site/templates/assets/css/source/vendor/gridle/gridle/_mixins.scss
>> 		%#{$stateName}-#{$for} {

**Comment by Milewski** [comment]
Me too.... any solution?

**Comment by mindfulmike** [comment]
`npm install --save-dev gulp-sass@2.3.1`. Lock the version and dont update. Since the node-sass guys broke semver.

**Comment by neonwired** [comment]
When I investigated further I found that It's actually an update to libsass that causes it so only rolling back gulp-sass might not roll back libsass

**Comment by olivierbossel** [comment]
Hi guys,
thanks for your feedback. Obviously we have had a lot of issues with the libsass semver mistakes. It has to be ok now.
Cheers!
