### ISSUE TITLE
Error - Segmentation fault: 11

### ISSUE THREAD

**Issue by kriss145** [Coffeekraken/gridle#125]
Hi,

I get error when I want to use "gridle_generate_custom_class" method.

Name error: "Segmentation fault: 11"

It error is on:
Node: 6.10.2
Gulp Sass: 3.1.0

@olivierbossel Could you help?

Thanks!

**Comment by olivierbossel** [comment]
Hi,
thanks for your feedback. Try to update to gridle 3.x as well as updating your node installation and give it another try cause it seems more like a node stack issue...
Cheers!
