### ISSUE TITLE
Demo Page does not work

### ISSUE THREAD

**Issue by piscis** [Coffeekraken/gridle#127]
opening the demo page leads to a 404 e.g. http://olivierbossel.github.io/gridle/demo.html

**Comment by TheCopartnery** [comment]
Yeah, would be great if the link could be be fixed.

Couldn't find where to submit a pull request but can access the demo via:

http://coffeekraken.github.io/gridle/demo.html

**Comment by Landish** [comment]
+1

**Comment by tcharlss** [comment]
+1

**Comment by olivierbossel** [comment]
thanks for the feedback guys, I will update that :)
