### ISSUE TITLE
Slight mistake in documentation

### ISSUE THREAD

**Issue by oma84** [Coffeekraken/gridle#129]
I just wanted to let you know, that there is a slight mistake in the "Get started" markdown file. It says to generate the classes one shall write "g-generate-classes()". But it seems, that this has been changed someday to "g-classes()".

I was able to find out the right syntax on the main page (readme-file) and surely everyone else will also be able to find out. Maybe you can correct this one day for convenience :)

**Comment by olivierbossel** [comment]
Hi,
thanks for the feedback. I will take a look.
Don't hesitate to make a pull request for this kind of issue, it will be nice to have the community help a bit by putting hands in the dirt :)
Cheers, thanks again :)

**Comment by oma84** [comment]
Oh okay, I am sorry. Will do so in future. :)
But will have to find out how to do a pull request first :D ... never did one.
