### ISSUE TITLE
NPM install doesn't work for some reason...

### ISSUE THREAD

**Issue by elron** [Coffeekraken/gridle#130]
Hey guys,

for some reason I can not install gridle through `npm install coffeekraken-gridle --save`.

I tried and it gave me this error:
```
D:\Desktop\Elron Apps\my_first_site>npm install coffeekraken-gridle --save
npm ERR! code ENOGIT
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Elron\AppData\Roaming\npm-cache\_logs\2017-12-23T15_56_46_261Z-debug.log
```
here's the log file: [2017-12-23T15_56_46_261Z-debug.log](https://github.com/Coffeekraken/gridle/files/1584239/2017-12-23T15_56_46_261Z-debug.log)

Any chance to help me understanding what I'm doing wrong?
Thanks!

PS gridle is life

**Comment by elron** [comment]
Ok now I installed git and tested `git --version` which worked.
So I tried to `npm install coffeekraken-gridle --save` again but now I get this error:

`D:\Desktop\Elron Apps\my_first_site>npm install coffeekraken-gridle --save

> coffeekraken-gridle@3.0.0-rc.2 install D:\Desktop\Elron Apps\my_first_site\node_modules\coffeekraken-gridle
> ./scripts/install.sh

'.' is not recognized as an internal or external command,
operable program or batch file.
npm WARN my_first_site@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! coffeekraken-gridle@3.0.0-rc.2 install: `./scripts/install.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the coffeekraken-gridle@3.0.0-rc.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Elron\AppData\Roaming\npm-cache\_logs\2017-12-23T17_24_18_056Z-debug.log`
Here's the log file: 
[2017-12-23T17_24_18_056Z-debug.log](https://github.com/Coffeekraken/gridle/files/1584317/2017-12-23T17_24_18_056Z-debug.log)

Help please!

**Comment by elron** [comment]
I get a sense that it is a problem with the command "./scripts/install.sh" - explained here:
[How to fix '.' is not an internal or external command error](https://stackoverflow.com/questions/20765337/how-to-fix-is-not-an-internal-or-external-command-error)

**Comment by olivierbossel** [comment]
Hi man,
Thanks for the feedback. I will take a look asap to your issue.
It must be something with windows difference from osx and linux environments.
I just have some Christmas stuffs to do before like eating way to much, etc... I will take a look asap and I come to you quickly :)
Cheers!

ps : you're not doing something wrong don't worry. The only thing that you can do better it to work on linux or osx ;) Your issue it just that I use the 'mv' command in the install.sh script that does not exist on windows it seems...

**Comment by elron** [comment]
No no, Thank YOU!
And bon apetit.

I actually consider getting a mac...  I fell into some unnecessary problems with node/npm in windows... ^_^"

**Comment by olivierbossel** [comment]
Hi,
You can try the 3.0.0-rc.3 versiion. I've rewrite the install script in nodejs instead of shell for better cross platform compatibility.
Let me know!

**Comment by elron** [comment]
Hey,
I tried again `npm install gridle` and it worked! 👍 Thanks :) 
I can find the gridle folder in "node_modules/gridle".

Now I just don't really understand how to add it to my project... how does it work? [quick start](https://www.npmjs.com/package/gridle#quick-start) says to `import "gridle/gridle"`, which sounds obvious but I don't understand where.
