### ISSUE TITLE
Broken google links

### ISSUE THREAD

**Issue by elron** [Coffeekraken/gridle#131]
You might want to know that some google links are broken.

https://www.google.co.il/search?safe=off&biw=1920&bih=949&ei=8A1AWvatJ5LNkwWQ07foBg&q=gridle+grid+system&oq=gridle+grid+system&gs_l=psy-ab.3..0i10i30k1l2.2455.2455.0.2967.1.1.0.0.0.0.158.158.0j1.1.0....0...1c.1.64.psy-ab..0.1.157....0.8_Hqiuu1mko

broken links:
http://gridle.org/documentation
http://gridle.org/documentation/1.3.3
http://gridle.org/documentation/1.3.1

By the way, I remember that gridle had its own BIG documentaion website (not on github). where did it go? 

Elron

**Comment by olivierbossel** [comment]
Thanks for the feedback.
I've removed the gridle.org website in favor of the markdown documentation in github. It's a lot easier to maintain for me cause the website takes me a lot of effort each time I make a new release.
I have a lot of other repositories to maintain as well so it's a nice to have for me.
You have all the documentation in the github repo by the way :) The website was just an interface on top of it.
For the google links, they will be updated once the google bot come check again the domain.
Thanks for you feedback again!
Cheers!
