### ISSUE TITLE
g-classes – prints css to the body

### ISSUE THREAD

**Issue by peunoir** [Coffeekraken/gridle#134]
Hey,
I can't get it to work. Every time I try to use `g-classes()` I get the css printed into the body of the page, but the `gr-` class working, if I don't use `g-classes()`, I get no css into the body but also `gr-` class won't work.
I can't figure out a way to make it work.

I used the setup from the demo. Using it in a nuxtjs app.

<img width="1440" alt="screen shot 2018-01-14 at 21 50 48" src="https://user-images.githubusercontent.com/3318683/34920151-c35b224c-f976-11e7-895a-8c9cc1ef44a6.png">

**Comment by olivierbossel** [comment]
Hi man,
Thanks for the feedback.
Without any more informations it will be hard for me to figure out what can be wrong.
Is that possible to recreate the issue in something like codepen, or at least send me your project files so I can take a look cause I don't have had this kind of issue for now..
Let me know!

**Comment by peunoir** [comment]
Hey @olivierbossel
Yes, I'll try to do that.
Fow now, I've made it work just by deleting part of a comment in the `/sass/_generate-mixins.scss`, lines from `612` to `620`. 
`* <style>`
` * #{_g-selector(row)}.gridle-styleguide {`
` * 	margin-bottom: #{g-get-state-var(gutter-width)};`
` * }`
` * #{_g-get-generic-selector(grid)}.gridle-styleguide {`
` * 	background:#eee;`
` * 	padding:#{g-get-state-var(gutter-width)};`
` * }`
` * </style>`

I'll try to find out more about what's causing this behaviour and come with another update.

**Comment by peunoir** [comment]
I've made another update, #137 , that fixes the issue.

**Comment by olivierbossel** [comment]
I man,
Thanks for the feedback again.
Can you compile your css without the comments? It can be cleaner to do that like so.
Don't have any issues on my side and I can't reproduce it.
Let me know!

ps : sorry for the delay

**Comment by homerjam** [comment]
I'm having this issue too. I'm trying to use Gridle with Nuxt. Under the hood webpack is used - I think it could be caused by the extractCSS plugin.

**Comment by homerjam** [comment]
I was able to get around this using `postcss-discard-comments`
