### ISSUE TITLE
Uncaught ReferenceError: exports is not defined at gridle.js:3

### ISSUE THREAD

**Issue by zitrusblau** [Coffeekraken/gridle#135]
Hi there,

I get the above error when using gridle.js
After a few hours of trial and error I found out that the npm module of gridle comes without the js source files and having only the compiled js files which gave me the above error.

Any help would be appreciated.

**Comment by olivierbossel** [comment]
Hi man,
Thanks for the feedback.
The package come with only the compiled ones and that's fine but there was an issue with the package.json "main" property. It was fixed in v3.0.1
I let you try again and let me know!
Cheers!

ps : sorry for the delay
