### ISSUE TITLE
Deprecation Warnings when compiling SCSS

### ISSUE THREAD

**Issue by zitrusblau** [Coffeekraken/gridle#136]
FYI
I get the following warnings when compiling SASS:
 DEPRECATION WARNING on line 596, column 8 of D:/xampp/htdocs/zitrus/gruene-fraktion-berlin/wp-content/themes/gruen/node_modules/coffeekraken-gridle/sass/_generate-mixins.scss:
Unescaped multiline strings are deprecated and will be removed in a future version of Sass.
To include a newline in a string, use "\a" or "\a " as in CSS.

DEPRECATION WARNING on line 597, column 78 of D:/xampp/htdocs/... /node_modules/coffeekraken-gridle/sass/_generate-mixins.scss:
Unescaped multiline strings are deprecated and will be removed in a future version of Sass.
To include a newline in a string, use "\a" or "\a " as in CSS.

DEPRECATION WARNING on line 598, column 74 of D:/xampp/htdocs/... /node_modules/coffeekraken-gridle/sass/_generate-mixins.scss:
Unescaped multiline strings are deprecated and will be removed in a future version of Sass.
To include a newline in a string, use "\a" or "\a " as in CSS.

DEPRECATION WARNING on line 599, column 43 of D:/xampp/htdocs/... /node_modules/coffeekraken-gridle/sass/_generate-mixins.scss:
Unescaped multiline strings are deprecated and will be removed in a future version of Sass.
To include a newline in a string, use "\a" or "\a " as in CSS.

Additional infos: I'm building a WordPress Theme with Gridle using Gulp and compiling SASS with gulp-ruby-sass.

**Comment by olivierbossel** [comment]
Hi man,
Thanks for the feedback.
This has been fixed in v3.0.1.
I let you try that and let me know!
Cheers!
