### ISSUE TITLE
in firefox all components become left to right align. 'div' positioning got reversed from left to right.

### ISSUE THREAD

**Issue by dreamwarrior** [Coffeekraken/gridle#138]
because of these lines:
./gridle/grid-settings.scss 
line 33: direction : rtl;

./gridle/gridle/_generate_mixins.scss
line 597: direction: gridle_get_state_var(direction);

after removing these two lines my application is working fine. Hoping you will check this issue out.

**Comment by olivierbossel** [comment]
Hi man,
thanks for the feedback.
Can you give me more info on your issue? I've tested on my firefox and I don't get this issue...
Is this line coming from the demo folder?
./gridle/grid-settings.scss
line 33: direction : rtl;

**Comment by dreamwarrior** [comment]
Sorry I for got add some meta data thus this issue arouse. I should close it down. Thanks for you response.
