### ISSUE TITLE
Can not import gridle-JS files

### ISSUE THREAD

**Issue by LudvikMichalek** [Coffeekraken/gridle#139]
I am unable to include/require/import module in my project. Tried in Webpack, tried to transpile/compile/browserify, but still no luck:

**Webpack include:**
`Module not found: Error: Can't resolve 'coffeekraken-gridle' in <...path...>`

**Browserify compile:**
`Error: Cannot find module 'coffeekraken-gridle' from <...path...>`

Can anyone give advice how to include the file in my project? Simple including of `dist/js/gridle.js` file in my HTML throws:
`ReferenceError: Can't find variable: exports`  (trying to run ES6 in browser)

Is there some bug in the packaging of JS files?

**Comment by olivierbossel** [comment]
I man,
Thanks for the feedback.
This was an issue inside the package itself. Normaly it's now ok in v3.0.1
Let me know!
