### ISSUE TITLE
line-height problem on columns

### ISSUE THREAD

**Issue by tcharlss** [Coffeekraken/gridle#140]
Hi,

I'm testing the latest 3.0 version, and I'm using the grid via mixins.
I noticed that columns now have the following line-height property :

`line-height: 1;`

Why is that necessary ? Because it ruins the typography.
I put the proper line-height on the `body` and it's supposed not to be changed anywhere else.
It would really be tedious to put back the proper line-height each time one set up columns.

**Comment by olivierbossel** [comment]
Hi man,
Thanks for the feedback.
This has been fixed in v3.0.1. Not sure why this was here but no problem to remove it.
Let me know!

**Comment by tcharlss** [comment]
Thanks a lot !
It's fine in v3.0.1 indeed.
