### ISSUE TITLE
Please export the package

### ISSUE THREAD

**Issue by dcdeiv** [Coffeekraken/gridle#144]
Can you please export the path package so that I can resolve the path via `includePath` and include the package in my main scss file just typing `@import "coffeekraken-gridle"` instead of `@import "../../../../../../node_modules/coffeekraken-gridle/index"`?

example:
[node-normalize-scss includePaths export rule](https://github.com/ranjandatta/node-normalize-scss/blob/master/index.js)
[bourbon includePath export rule](https://github.com/thoughtbot/bourbon/blob/master/index.js)

**Comment by olivierbossel** [comment]
Hi,
Sorry for the delay. I've been pretty busy this year.
With what are you compiling your sass files? You can use the "include-path" cli command if you're using the node-sass package.
I will investigate your solution but as I already have a "main" in my package.json file I'm not sure I can easily add your solution. Will see..
Thanks by the way for the idea
Cheers
